'use strict';

const net = require('node:net');
const { emitDiagnostic } = require('../system/runtime-diagnostic-bus');
const { normalizeModelCatalogEntry } = require('./ModelCatalog');

const ENDPOINT_POLICIES = Object.freeze({ LOOPBACK:'loopback', PRIVATE_NETWORK:'private-network', ANY_HTTP:'any-http' });
function normalizeEndpointPolicy(value) { const policy=String(value||ENDPOINT_POLICIES.PRIVATE_NETWORK).trim().toLowerCase(); if(!Object.values(ENDPOINT_POLICIES).includes(policy))throw new Error(`Unsupported LM Studio endpoint policy: ${policy}`); return policy; }
function isLoopbackHost(hostname) { const host=String(hostname||'').replace(/^\[|\]$/gu,'').toLowerCase(); return host==='localhost'||host==='::1'||/^127(?:\.\d{1,3}){3}$/u.test(host); }
function isPrivateNetworkHost(hostname) { const host=String(hostname||'').replace(/^\[|\]$/gu,'').toLowerCase(); if(isLoopbackHost(host)||host.endsWith('.local'))return true; const family=net.isIP(host); if(family===4){const p=host.split('.').map(Number);return p[0]===10||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===169&&p[1]===254);} if(family===6)return host.startsWith('fc')||host.startsWith('fd')||host.startsWith('fe80:'); return false; }
function normalizeBaseUrl(value, endpointPolicy=ENDPOINT_POLICIES.PRIVATE_NETWORK){const url=new URL(String(value||'').trim());if(!['http:','https:'].includes(url.protocol))throw new Error('LM Studio base URL must use HTTP or HTTPS.');const policy=normalizeEndpointPolicy(endpointPolicy);if(policy===ENDPOINT_POLICIES.LOOPBACK&&!isLoopbackHost(url.hostname))throw new Error('LM Studio endpoint policy allows loopback hosts only.');if(policy===ENDPOINT_POLICIES.PRIVATE_NETWORK&&!isPrivateNetworkHost(url.hostname))throw new Error('LM Studio endpoint policy allows loopback or private-network hosts only.');url.pathname=url.pathname.replace(/\/+$/u,'');return url;}
function withV1Path(baseUrl,pathName,endpointPolicy){const url=normalizeBaseUrl(baseUrl,endpointPolicy);const base=url.pathname.replace(/\/+$/u,'');url.pathname=/\/v1$/iu.test(base)?base:`${base}/v1`;url.pathname=`${url.pathname}/${String(pathName||'').replace(/^\/+/, '')}`;return url.toString();}
function requestHeaders(apiKey,extra={}){return{...extra,...(apiKey?{Authorization:`Bearer ${apiKey}`}:{})};}

class OpenAICompatibleProvider {
  constructor(cfg={}) {
    this.baseUrl=cfg.baseUrl||'';this.model=cfg.model||'';this.apiKey=cfg.apiKey||'';this.providerId=String(cfg.providerId||'openai-compatible').trim()||'openai-compatible';this.providerKind=String(cfg.providerKind||'openai-compatible').trim()||'openai-compatible';this.local=cfg.local===true;this.endpointPolicy=normalizeEndpointPolicy(cfg.endpointPolicy);this.contextLength=positiveInteger(cfg.contextLength);this.ttlSeconds=positiveInteger(cfg.ttlSeconds);this.fetch=cfg.fetch||global.fetch;this.timeoutMs=Number(cfg.timeoutMs)||180000;
    this.health={configured:false,reachable:false,healthy:false,modelAvailable:false,modelCount:0,lastCheckedAt:null,lastSuccessAt:null,failureReason:null,capabilities:{completion:'unknown',toolCalling:'unknown',structuredOutput:'unknown'}};
  }
  getHealth(){return JSON.parse(JSON.stringify(this.health));}
  async checkHealth(){this.health.lastCheckedAt=new Date().toISOString();if(!this.baseUrl||!this.model){Object.assign(this.health,{configured:false,reachable:false,healthy:false,modelAvailable:false,failureReason:'Provider base URL or model is not configured.'});return this.getHealth();}this.health.configured=true;try{const models=await this.listModels();this.health.reachable=true;this.health.modelCount=models.length;this.health.modelAvailable=models.includes(this.model);this.health.healthy=this.health.modelAvailable;this.health.failureReason=this.health.modelAvailable?null:`Selected model is not available from the provider: ${this.model}`;if(this.health.healthy)this.health.lastSuccessAt=new Date().toISOString();}catch(error){this.health.reachable=false;this.health.healthy=false;this.health.modelAvailable=false;this.health.failureReason=error?.message||String(error);}return this.getHealth();}
  assertConfigured(){if(!this.baseUrl)throw new Error('Provider base URL is not configured.');if(!this.model)throw new Error('Provider model is not selected.');}
  chatCompletionsUrl(){return withV1Path(this.baseUrl,'chat/completions',this.endpointPolicy);}
  async listModelCatalog(){if(!this.baseUrl)throw new Error('Provider base URL is not configured.');const started=Date.now();try{const response=await this.fetch(withV1Path(this.baseUrl,'models',this.endpointPolicy),{method:'GET',headers:requestHeaders(this.apiKey,{Accept:'application/json'})});const text=await response.text();if(!response.ok)throw providerError('PROVIDER_MODELS_ERROR',responseMessage(response.status,text));let payload;try{payload=JSON.parse(text);}catch{throw providerError('PROVIDER_INVALID_JSON','Provider models endpoint returned invalid JSON.');}const models=Array.isArray(payload?.data)?payload.data:(Array.isArray(payload?.models)?payload.models:[]);const seen=new Set();const catalog=[];for(const model of models){const id=String(model?.id||model?.key||'').trim();if(!id||seen.has(id))continue;seen.add(id);catalog.push(normalizeModelCatalogEntry({providerId:this.providerId,providerKind:this.providerKind,modelId:id,info:model||{},local:this.local}));}catalog.sort((left,right)=>left.id.localeCompare(right.id));emitDiagnostic({source:'openai-provider',category:'provider',action:'list_models',phase:'success',durationMs:Date.now()-started,data:{modelCount:catalog.length,selectedModel:this.model}});return catalog;}catch(error){emitDiagnostic({source:'openai-provider',category:'provider',action:'list_models',phase:'failed',durationMs:Date.now()-started,error});throw error;}}
  async listModels(){return(await this.listModelCatalog()).map(item=>item.id);}
  async complete({messages,tools,responseFormat,signal,correlation}={}){
    this.assertConfigured();const body={model:this.model,messages,stream:false,temperature:0};if(this.contextLength)body.context_length=this.contextLength;if(this.ttlSeconds)body.ttl=this.ttlSeconds;if(responseFormat)body.response_format=responseFormat;if(Array.isArray(tools)&&tools.length){body.tools=tools;body.tool_choice='auto';}
    const controller=new AbortController();const abortFromCaller=()=>controller.abort(signal?.reason);if(signal?.aborted)abortFromCaller();else if(signal&&typeof signal.addEventListener==='function')signal.addEventListener('abort',abortFromCaller,{once:true});const timer=setTimeout(()=>controller.abort(),this.timeoutMs);let response;const started=Date.now();
    emitDiagnostic({source:'openai-provider',category:'provider',action:'completion',phase:'start',correlation,data:{model:this.model,toolCount:Array.isArray(tools)?tools.length:0,structuredOutput:Boolean(responseFormat)}});
    try{response=await this.fetch(this.chatCompletionsUrl(),{method:'POST',headers:requestHeaders(this.apiKey,{'Content-Type':'application/json'}),body:JSON.stringify(body),signal:controller.signal});}catch(error){if(error?.name==='AbortError')error=providerError('PROVIDER_TIMEOUT',`Provider request timed out after ${this.timeoutMs} ms.`);emitDiagnostic({source:'openai-provider',category:'provider',action:'completion',phase:'failed',durationMs:Date.now()-started,correlation,error});throw error;}finally{clearTimeout(timer);if(signal&&typeof signal.removeEventListener==='function')signal.removeEventListener('abort',abortFromCaller);}
    const text=await response.text();if(!response.ok){const error=providerError('PROVIDER_ERROR',responseMessage(response.status,text),{httpStatus:response.status});emitDiagnostic({source:'openai-provider',category:'provider',action:'completion',phase:'failed',durationMs:Date.now()-started,correlation,error});throw error;}
    let payload;try{payload=JSON.parse(text);}catch{const error=providerError('PROVIDER_INVALID_JSON','Provider returned invalid JSON.');emitDiagnostic({source:'openai-provider',category:'provider',action:'completion',phase:'failed',durationMs:Date.now()-started,correlation,error});throw error;}
    const choice=payload?.choices?.[0]||{};const message=choice.message||{};const content=String(message.content||'').trim()||null;const toolCalls=Array.isArray(message.tool_calls)?message.tool_calls.map((tc,index)=>({id:String(tc.id||`tool-call-${index+1}`),name:String(tc.function?.name||'').trim(),arguments:parseToolArguments(tc.function?.arguments,tc.function?.name)})).filter(tc=>tc.name):[];
    const providerRequestId=String(payload?.id||response.headers?.get?.('x-request-id')||response.headers?.get?.('request-id')||'')||null;const native={providerRequestId,providerEventType:String(payload?.object||'chat.completion'),providerStopReason:choice.finish_reason==null?null:String(choice.finish_reason),modelId:String(payload?.model||this.model)};
    Object.assign(this.health,{reachable:true,healthy:true,configured:true,modelAvailable:true,lastCheckedAt:new Date().toISOString(),lastSuccessAt:new Date().toISOString(),failureReason:null});
    emitDiagnostic({source:'openai-provider',category:'provider',action:'completion',phase:'success',durationMs:Date.now()-started,correlation:{...(correlation||{}),providerRequestId},data:{model:native.modelId,toolCalls:toolCalls.map(tc=>tc.name),usage:payload?.usage||null,native}});
    return {content,toolCalls,model:native.modelId,usage:payload?.usage||null,...native};
  }
}
function positiveInteger(value){const number=Number(value);return Number.isInteger(number)&&number>0?number:null;}
function parseToolArguments(value,toolName=''){const source=String(value??'').trim();if(!source)return{};let parsed;try{parsed=JSON.parse(source);}catch{throw providerError('PROVIDER_TOOL_ARGUMENTS_INVALID',`Provider returned invalid JSON arguments for tool ${toolName||'(unknown)'}.`);}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw providerError('PROVIDER_TOOL_ARGUMENTS_INVALID',`Provider returned non-object arguments for tool ${toolName||'(unknown)'}.`);return parsed;}
function safeParseArgs(value){return parseToolArguments(value);}
function responseMessage(status,text){let message=`Provider responded ${status}.`;try{message=JSON.parse(text)?.error?.message||message;}catch{if(text)message=text;}return String(message).slice(0,1800);}
function providerError(code,message,metadata={}){const error=new Error(message);error.code=code;Object.assign(error,metadata);return error;}
module.exports=OpenAICompatibleProvider;module.exports.ENDPOINT_POLICIES=ENDPOINT_POLICIES;module.exports.normalizeEndpointPolicy=normalizeEndpointPolicy;module.exports.normalizeBaseUrl=normalizeBaseUrl;module.exports.isLoopbackHost=isLoopbackHost;module.exports.isPrivateNetworkHost=isPrivateNetworkHost;module.exports.parseToolArguments=parseToolArguments;module.exports.safeParseArgs=safeParseArgs;
